///////////////////////////////////////////////////////////////////////////////
// Header guard
///////////////////////////////////////////////////////////////////////////////
#pragma once

///////////////////////////////////////////////////////////////////////////////
// Dependencies
///////////////////////////////////////////////////////////////////////////////
#include "../../../Arcade/utils/Vec2.hpp"
#include <vector>
#include "games/NIBBLER/Assets.hpp"

namespace Arc::Nibbler
{

static const std::vector<std::vector<SpriteType>> MAP_01 = {
    { // colums 1
        BORDER_IN_BR, WALL_LEFT, WALL_LEFT, WALL_LEFT, WALL_LEFT, WALL_LEFT, WALL_LEFT, WALL_LEFT,
        WALL_LEFT, WALL_LEFT, WALL_LEFT, WALL_LEFT, WALL_LEFT, WALL_LEFT, WALL_LEFT, WALL_LEFT,
        WALL_LEFT, WALL_LEFT, WALL_LEFT, WALL_LEFT, WALL_LEFT, WALL_LEFT,
        WALL_LEFT, WALL_LEFT, WALL_LEFT, WALL_LEFT, BORDER_IN_TR
    },
    { // colums 2
        WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
        EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
        EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
        EMPTY, EMPTY, EMPTY, EMPTY, WALL_BOT
    },
    { // colums 3
        WALL_TOP, EMPTY, BORDER_OUT_BR, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT,
        BORDER_OUT_TR, EMPTY, BORDER_OUT_BR, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT,
        BORDER_OUT_TR, EMPTY, BORDER_OUT_BR, BORDER_OUT_TR, EMPTY, BORDER_OUT_BR,
        WALL_RIGHT, WALL_RIGHT, WALL_RIGHT, BORDER_OUT_TR, EMPTY, BORDER_OUT_BR,
        BORDER_OUT_TR, EMPTY, WALL_BOT,
    },
    { // colums 4
        WALL_TOP, EMPTY, WALL_BOT, BORDER_IN_BR, WALL_LEFT, BORDER_IN_TR,
        WALL_TOP, EMPTY, WALL_BOT, BORDER_IN_BR,
        WALL_LEFT, WALL_LEFT, BORDER_OUT_TL, EMPTY, WALL_BOT, WALL_TOP,
        EMPTY, WALL_BOT, BORDER_IN_BR, WALL_LEFT, BORDER_IN_TR, WALL_TOP,
        EMPTY, WALL_BOT, WALL_TOP, EMPTY, WALL_BOT
    },
    { // colums 5
        WALL_TOP, EMPTY, WALL_BOT, WALL_TOP, EMPTY, WALL_BOT, WALL_TOP,
        EMPTY, WALL_BOT, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_BOT,
        WALL_TOP, EMPTY, WALL_BOT, WALL_TOP, EMPTY, WALL_BOT, WALL_TOP,
        EMPTY, WALL_BOT, WALL_TOP, EMPTY, WALL_BOT
    },
    { // colums 6
        WALL_TOP, EMPTY, WALL_BOT, BORDER_IN_BL, WALL_RIGHT, BORDER_IN_TL,
        WALL_TOP, EMPTY, WALL_BOT, WALL_TOP, EMPTY, BORDER_OUT_BR,
        BORDER_OUT_TR, EMPTY, WALL_BOT, WALL_TOP, EMPTY, WALL_BOT,
        BORDER_IN_BL, WALL_RIGHT, BORDER_IN_TL, WALL_TOP,
        EMPTY, WALL_BOT, WALL_TOP, EMPTY, WALL_BOT
    },
    { // colums 7
        WALL_TOP, EMPTY, BORDER_OUT_BL, WALL_LEFT, WALL_LEFT, WALL_LEFT,
        BORDER_OUT_TL, EMPTY, WALL_BOT, WALL_TOP, EMPTY, WALL_BOT, WALL_TOP,
        EMPTY, WALL_BOT, WALL_TOP, EMPTY, BORDER_OUT_BL, WALL_LEFT,
        WALL_LEFT, WALL_LEFT, BORDER_OUT_TL, EMPTY, WALL_BOT, WALL_TOP,
        EMPTY, WALL_BOT
    },
    { // colums 8
        WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
        WALL_BOT, WALL_TOP, EMPTY, WALL_BOT, WALL_TOP, EMPTY, WALL_BOT,
        WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
        WALL_BOT, WALL_TOP, EMPTY, WALL_BOT
    },
    { // colums 9
        WALL_TOP, EMPTY, BORDER_OUT_BR, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT,
        WALL_RIGHT, WALL_RIGHT, BORDER_IN_TL, WALL_TOP, EMPTY, WALL_BOT,
        WALL_TOP, EMPTY, WALL_BOT, WALL_TOP, EMPTY, BORDER_OUT_BR,
        WALL_RIGHT, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT,
        BORDER_IN_TL, WALL_TOP, EMPTY, WALL_BOT
    },
    { // colums 10
        WALL_TOP, EMPTY, BORDER_OUT_BL, WALL_LEFT, WALL_LEFT, WALL_LEFT,
        WALL_LEFT, WALL_LEFT,WALL_LEFT,  BORDER_OUT_TL, EMPTY, WALL_BOT,
        WALL_TOP, EMPTY, BORDER_OUT_BL, BORDER_OUT_TL, EMPTY, BORDER_OUT_BL,
        WALL_LEFT, WALL_LEFT, WALL_LEFT, WALL_LEFT, WALL_LEFT, WALL_LEFT,
        BORDER_OUT_TL, EMPTY, WALL_BOT
    },
    { // colums 11
        WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
        EMPTY, EMPTY, WALL_BOT, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY,
        EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
        WALL_BOT
    },
    { // colums 12
        WALL_TOP, EMPTY, BORDER_OUT_BR, BORDER_OUT_TR, EMPTY, BORDER_OUT_BR,
        WALL_RIGHT, WALL_RIGHT, WALL_RIGHT, BORDER_OUT_TR, EMPTY, WALL_BOT,
        WALL_TOP, EMPTY, BORDER_OUT_BR, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT,
        BORDER_OUT_TR, EMPTY, BORDER_OUT_BR, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT,
        BORDER_OUT_TR, EMPTY, WALL_BOT
    },
    { // colums 13
        WALL_TOP, EMPTY, WALL_BOT, WALL_TOP, EMPTY, BORDER_OUT_BL,
        WALL_LEFT, WALL_LEFT, WALL_LEFT, BORDER_OUT_TL, EMPTY, BORDER_OUT_BL,
        BORDER_OUT_TL, EMPTY, WALL_BOT, BORDER_IN_BR, WALL_LEFT, BORDER_IN_TR,
        WALL_TOP, EMPTY, WALL_BOT, BORDER_IN_BR, WALL_LEFT, BORDER_IN_TR,
        WALL_TOP, EMPTY, WALL_BOT
    },
    { // colums 14
        WALL_TOP, EMPTY, WALL_BOT, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY,
        EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL_BOT, WALL_TOP,
        EMPTY, WALL_BOT, WALL_TOP, EMPTY, WALL_BOT, WALL_TOP,
        EMPTY, WALL_BOT, WALL_TOP, EMPTY, WALL_BOT
    },
    { // colums 15 = 13
        WALL_TOP, EMPTY, WALL_BOT, WALL_TOP, EMPTY, BORDER_OUT_BR,
        WALL_RIGHT, WALL_RIGHT, WALL_RIGHT, BORDER_OUT_TR, EMPTY, BORDER_OUT_BR,
        BORDER_OUT_TR, EMPTY, WALL_BOT, BORDER_IN_BL, WALL_RIGHT, BORDER_IN_TL,
        WALL_TOP, EMPTY, WALL_BOT, BORDER_IN_BL, WALL_RIGHT, BORDER_IN_TL,
        WALL_TOP, EMPTY, WALL_BOT
    },
    { // colums 16 = 12
        WALL_TOP, EMPTY, BORDER_OUT_BL, BORDER_OUT_TL, EMPTY, BORDER_OUT_BL,
        WALL_LEFT, WALL_LEFT, WALL_LEFT, BORDER_OUT_TL, EMPTY, WALL_BOT,
        WALL_TOP, EMPTY, BORDER_OUT_BL, WALL_LEFT, WALL_LEFT, WALL_LEFT,
        BORDER_OUT_TL, EMPTY, BORDER_OUT_BL, WALL_LEFT, WALL_LEFT, WALL_LEFT,
        BORDER_OUT_TL, EMPTY, WALL_BOT
    },
    { // colums 17 = 11
        WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
        EMPTY, EMPTY, WALL_BOT, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY,
        EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
        WALL_BOT
    },
    { // colums 18 = 10
        WALL_TOP, EMPTY, BORDER_OUT_BR, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT,
        WALL_RIGHT, WALL_RIGHT, WALL_RIGHT, BORDER_OUT_TR, EMPTY, WALL_BOT,
        WALL_TOP, EMPTY, BORDER_OUT_BR, BORDER_OUT_TR, EMPTY, BORDER_OUT_BR,
        WALL_RIGHT, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT,
        BORDER_OUT_TR, EMPTY, WALL_BOT
    },
    { // colums 19 = 9
        WALL_TOP, EMPTY, BORDER_OUT_BL, WALL_LEFT, WALL_LEFT, WALL_LEFT,
        WALL_LEFT, WALL_LEFT, BORDER_IN_TR, WALL_TOP, EMPTY, WALL_BOT,
        WALL_TOP, EMPTY, WALL_BOT, WALL_TOP, EMPTY, BORDER_OUT_BL,
        WALL_LEFT, WALL_LEFT, WALL_LEFT, WALL_LEFT, WALL_LEFT,
        BORDER_IN_TR, WALL_TOP, EMPTY, WALL_BOT
    },
    { // colums 20 = 8
        WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
        WALL_BOT, WALL_TOP, EMPTY, WALL_BOT, WALL_TOP, EMPTY, WALL_BOT,
        WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
        WALL_BOT, WALL_TOP, EMPTY, WALL_BOT
    },
    { // colums 21 = 7
        WALL_TOP, EMPTY, BORDER_OUT_BR, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT,
        BORDER_OUT_TR, EMPTY, WALL_BOT, WALL_TOP, EMPTY, WALL_BOT, WALL_TOP,
        EMPTY, WALL_BOT, WALL_TOP, EMPTY, BORDER_OUT_BR, WALL_RIGHT,
        WALL_RIGHT, WALL_RIGHT, BORDER_OUT_TR, EMPTY, WALL_BOT, WALL_TOP,
        EMPTY, WALL_BOT
    },
    { // colums 22 = 6
        WALL_TOP, EMPTY, WALL_BOT, BORDER_IN_BR, WALL_LEFT, BORDER_IN_TR,
        WALL_TOP, EMPTY, WALL_BOT, WALL_TOP, EMPTY, BORDER_OUT_BL,
        BORDER_OUT_TL, EMPTY, WALL_BOT, WALL_TOP, EMPTY, WALL_BOT,
        BORDER_IN_BR, WALL_LEFT, BORDER_IN_TR, WALL_TOP,
        EMPTY, WALL_BOT, WALL_TOP, EMPTY, WALL_BOT
    },
    { // colums 23 = 5
        WALL_TOP, EMPTY, WALL_BOT, WALL_TOP, EMPTY, WALL_BOT, WALL_TOP,
        EMPTY, WALL_BOT, WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, WALL_BOT,
        WALL_TOP, EMPTY, WALL_BOT, WALL_TOP, EMPTY, WALL_BOT, WALL_TOP,
        EMPTY, WALL_BOT, WALL_TOP, EMPTY, WALL_BOT
    },
    { // colums 24 = 4
        WALL_TOP, EMPTY, WALL_BOT, BORDER_IN_BL, WALL_RIGHT, BORDER_IN_TL,
        WALL_TOP, EMPTY, WALL_BOT, BORDER_IN_BL,
        WALL_RIGHT, WALL_RIGHT, BORDER_OUT_TR, EMPTY, WALL_BOT, WALL_TOP,
        EMPTY, WALL_BOT, BORDER_IN_BL, WALL_RIGHT, BORDER_IN_TL, WALL_TOP,
        EMPTY, WALL_BOT, WALL_TOP, EMPTY, WALL_BOT
    },
    { // colums 25 = 3
        WALL_TOP, EMPTY, BORDER_OUT_BL, WALL_LEFT, WALL_LEFT, WALL_LEFT,
        BORDER_OUT_TL, EMPTY, BORDER_OUT_BL, WALL_LEFT, WALL_LEFT, WALL_LEFT,
        BORDER_OUT_TL, EMPTY, BORDER_OUT_BL, BORDER_OUT_TL, EMPTY, BORDER_OUT_BL,
        WALL_LEFT, WALL_LEFT, WALL_LEFT, BORDER_OUT_TL, EMPTY, BORDER_OUT_BL,
        BORDER_OUT_TL, EMPTY, WALL_BOT,
    },
    { // colums 26 = 2
        WALL_TOP, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
        EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
        EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
        EMPTY, EMPTY, EMPTY, EMPTY, WALL_BOT
    },
    { // colums 27 = 1
        BORDER_IN_BL, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT,
        WALL_RIGHT, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT,
        WALL_RIGHT, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT,
        WALL_RIGHT, WALL_RIGHT, WALL_RIGHT, WALL_RIGHT, BORDER_IN_TL
    },
};

static const std::vector<Vec2i> MAP_01_FRUIT = {
    {5, 1}, {10, 1}, {16, 1}, {21, 1},
    {1, 5}, {7, 5}, {19, 5}, {25, 5},
    {10, 7}, {16, 7},
    {1, 10}, {6, 10}, {20, 10}, {25, 10},
    {13, 12},
    {6, 13}, {20, 13},
    {5, 16}, {21, 16},
    {13, 19},
    {1, 21}, {7, 21}, {10, 21}, {16, 21}, {19, 21}, {25, 21},
    {1, 23}, {25, 23}
};

} // namespace Arc::Nibbler